version: '2'

services:
  app:
    image: evitafernandez/docker-testing
    environment:
      MONGO_URL: "mongodb://db/test"
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: mongo
